export enum AMENITIES {
  SWIMMING_POOL = 'SWIMMING_POOL',
  GYM = 'GYM',
  PARKING = 'PARKING',
  ELEVATOR = 'ELEVATOR',
  SECURITY = 'SECURITY',
  PLAYGROUND = 'PLAYGROUND',
  GARDEN = 'GARDEN',
  AIR_CONDITIONING = 'AIR_CONDITIONING',
  BALCONY = 'BALCONY',
  PET_FRIENDLY = 'PET_FRIENDLY',
  WIFI = 'WIFI',
  FURNISHED = 'FURNISHED',
  CLUBHOUSE = 'CLUBHOUSE',
  TENNIS_COURT = 'TENNIS_COURT',
  SPA = 'SPA',
  BBQ_AREA = 'BBQ_AREA',
  SAUNA = 'SAUNA',
  STORAGE = 'STORAGE',
  MAID_SERVICE = 'MAID_SERVICE',
  LAUNDRY_SERVICE = 'LAUNDRY_SERVICE',
  ROOFTOP_TERRACE = 'ROOFTOP_TERRACE',
  BUSINESS_CENTER = 'BUSINESS_CENTER',
  SMART_HOME = 'SMART_HOME',
  CONCIERGE = 'CONCIERGE',
  CYCLING_TRACK = 'CYCLING_TRACK',
  JOGGING_TRACK = 'JOGGING_TRACK',
  PRIVATE_BEACH = 'PRIVATE_BEACH',
  CHILD_CARE = 'CHILD_CARE',
  LIBRARY = 'LIBRARY',
  THEATER = 'THEATER',
}

export enum PAYMENT_OPTIONS {
  INSTALLMENT_SETTLEMENT = 'INSTALLMENT_SETTLEMENT',
  FULL_SETTLEMENT = 'FULL_SETTLEMENT',
}

export enum STATUS {
  APPROVED = 'APPROVED',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
}

export enum DOCUMENT_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}
